config/routes.rb
Rails.application.routes.draw do
  resources :quantities
  resources :categories
  resources :ingredients
  resources :recipes
  root 'categories#index'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  # has_and_belongs_to_many :ingredients
  belongs_to :category

  has_many :quantities
  has_many :ingredients, through: :quantities

  def self.most_popular
    all.order("clickcount DESC").first
  end


  def increment_clickcount()
    if !self.clickcount
      self.clickcount = 0
    end
    # self.clickcount ||= 0
    self.clickcount += 1
    save
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    if params[:category_id]
      @recipes = Recipe.where(category_id: params[:category_id])
    else
      @recipes = Recipe.all
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe.increment_clickcount
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :instructions, :category_id, {:ingredient_ids => []})
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<div class='container'>
<div class='holder'>
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :instructions %><br>
    <%= f.text_field :instructions %>
  </div>
<!--   <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div> -->
  <div class="field">
    <%= f.label :category_id %><br>
    <%#= f.select :category_id, options_from_collection_for_select(Category.all, 'id', 'name') %>
    <%= f.select("category_id", Category.all.map {|c| [c.name, c.id]}) %>
  </div>
  <div class="field">
    <%= f.label :ingredient_id %><br>
    <%= f.collection_check_boxes(:ingredient_ids, Ingredient.all, :id, :name) %>
  </div>

  <div class="actions">
    <%= f.submit class: "button" %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'form' %>

<h1>Editing Recipe</h1>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<div class='container'>
  <div class='holder'>
  <h1>Recipes</h1>
    <% @recipes.each do |recipe| %>
        <%= link_to(recipe.name, recipe_path(recipe)) %>   
    <% end %>


<br>

<%= link_to 'New Recipe', new_recipe_path, class: "button" %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
<%= render 'form' %>


<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>
<div class='container'>
  <div class='holder'>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Instructions:</strong>
  <%= @recipe.instructions %>
</p>

<p>
  <strong>Category:</strong>
  <%= @recipe.category.try(:name) %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%# ingredients = Ingredient.find(@recipe.ingredient_ids)%>
  <%#= names = ingredients.map { |ingredient| ingredient[:name]}.join(" - ") %>
  <% @recipe.quantities.each do |quantity| %>   
    <%= quantity.quantity %>
    <%= quantity.ingredient.try(:name) %><br>
  <% end %>
</p>


<%= link_to 'Destroy', @recipe, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Edit', edit_recipe_path(@recipe) %> 
<%= link_to 'Back', recipes_path %>