config/routes.rb
Rails.application.routes.draw do
  resources :quantities
  resources :categories
  resources :ingredients
  resources :recipes
  root 'categories#index'

end

app/models/quantity.rb
class Quantity < ActiveRecord::Base
  belongs_to :ingredient
  belongs_to :recipe
end

app/controllers/quantities_controller.rb
class QuantitiesController < ApplicationController
  before_action :set_quantity, only: [:show, :edit, :update, :destroy]

  # GET /quantities
  # GET /quantities.json
  def index
    @quantities = Quantity.all
  end

  # GET /quantities/1
  # GET /quantities/1.json
  def show
  end

  # GET /quantities/new
  def new
    @quantity = Quantity.new
  end

  # GET /quantities/1/edit
  def edit
  end

  # POST /quantities
  # POST /quantities.json
  def create
    @quantity = Quantity.new(quantity_params)

    respond_to do |format|
      if @quantity.save
        format.html { redirect_to @quantity, notice: 'Quantity was successfully created.' }
        format.json { render :show, status: :created, location: @quantity }
      else
        format.html { render :new }
        format.json { render json: @quantity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quantities/1
  # PATCH/PUT /quantities/1.json
  def update
    respond_to do |format|
      if @quantity.update(quantity_params)
        format.html { redirect_to @quantity, notice: 'Quantity was successfully updated.' }
        format.json { render :show, status: :ok, location: @quantity }
      else
        format.html { render :edit }
        format.json { render json: @quantity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quantities/1
  # DELETE /quantities/1.json
  def destroy
    @quantity.destroy
    respond_to do |format|
      format.html { redirect_to quantities_url, notice: 'Quantity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quantity
      @quantity = Quantity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quantity_params
      params.require(:quantity).permit(:ingredient_id, :recipe_id, :quantity)
    end
end

app/helpers/quantities_helper.rb
module QuantitiesHelper
end

app/views/quantities/_form.html.erb
<div class='container'>
<div class='holder'>

<%= form_for(@quantity) do |f| %>
  <% if @quantity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quantity.errors.count, "error") %> prohibited this quantity from being saved:</h2>

      <ul>
      <% @quantity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--   <div class="field">
    <%= f.label :ingredient_id %><br>
    <%= f.number_field :ingredient_id %>
  </div>
  <div class="field">
    <%= f.label :recipe_id %><br>
    <%= f.number_field :recipe_id %>
  </div> -->
  <div class="field">
    <%= f.collection_select(:ingredient_id, Ingredient.all, :id, :name) %><br>
  </div>
  <div class="field">
    <%= f.collection_select(:recipe_id, Recipe.all, :id, :name) %><br>
  </div>

  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quantities/edit.html.erb
<h1>Editing Quantity</h1>

<%= render 'form' %>

<%= link_to 'Show', @quantity %> |
<%= link_to 'Back', quantities_path %>

app/views/quantities/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Quantities</h1>
<div class='container'>
<div class='holder'>


  <tbody>
    <% @quantities.each do |quantity| %>
      <tr>
        <td><%= quantity.ingredient.try(:name) %></td>
        
        <td><%= link_to 'Show', quantity %></td>
        <td><%= link_to 'Edit', edit_quantity_path(quantity) %></td>
        <td><%= link_to 'Destroy', quantity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

<br>

<%= link_to 'New Quantity', new_quantity_path %>

app/views/quantities/new.html.erb
<h1>New Quantity</h1>

<%= render 'form' %>

<%= link_to 'Back', quantities_path %>

app/views/quantities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ingredient:</strong>
  <%= @quantity.ingredient.try(:name) %>
</p>

<p>
  <strong>Recipe:</strong>
  <%= @quantity.recipe.try(:name) %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @quantity.quantity %>
</p>

<%= link_to 'Edit', edit_quantity_path(@quantity) %> |
<%= link_to 'Back', quantities_path %>